https://github.com/vostok/applications.scheduled/issues/1
vostok/applications.scheduled pull request #14
Opened 2021-05-06 18:12 UTC by iloktionov

2021-05-11 14:49 UTC, kungasc requested changes

2021-05-11 14:49 UTC, kungasc commented on Vostok.Applications.Scheduled/IScheduledActionsRunner.cs
> +    public interface IScheduledActionsRunner : IDisposable
вроде везде раньше не расширяли так интерфейсы, а вызывали (x as IDisposable)?.Dispose()

2021-05-11 14:49 UTC, kungasc commented on Vostok.Applications.Scheduled/ScheduledActionRunner.cs
> +        private volatile ScheduledAction action;
Надо бы читать эту штуку более умно.

Например в GetInfo может прочитаться что-то неконсистентное.

Или начаться выполняться с одним экшеном, а в ExecutePayload уже закончится с другим.

2021-05-11 14:49 UTC, kungasc commented on Vostok.Applications.Scheduled/ScheduledActionsBuilder.cs
> +                throw new InvalidOperationException("Dynamic and static configuration modes can't be mixed.");
Думаю будет удобным как раз мешать часть постоянных (логирование стейта) с динамическими (чтение почтовых ящиков).

Почему бы их не померджить?

2021-05-11 14:49 UTC, kungasc commented on Vostok.Applications.Scheduled/ScheduledActionsBuilder.cs
> +            dynamicOptions = new ScheduledActionsDynamicOptions(configuration, actualizationPeriod);
А вот тут можно уже кидать исключение, если уже были заполненные dynamicOptions.

2021-05-11 14:49 UTC, KungA commented on Vostok.Applications.Scheduled/ScheduledActionsBuilder.cs
> +        internal List<ScheduledAction> Actions { get; }
Наружу лучше IReadonlyList, а то ещё добавят туда чего.

2021-05-11 14:49 UTC, KungA commented on Vostok.Applications.Scheduled/Schedulers/PeriodicalScheduler.cs
> +        public void TryCopyStateFrom(IStatefulScheduler other)
Кажется при использовании jitter, достаточно большого периода и маленького времени актуализации, экшен будет выполнятся чаще, чем задумано :(

2021-05-11 14:49 UTC, KungA commented on Vostok.Applications.Scheduled/ScheduledActionsDynamicRunner.cs
> +                    if (runner.CanBeUpdated)
А зачем эта проверка? кажется ничего плохого не случится, если мы у уже завершенного ранера вызовем Update

2021-05-11 14:56 UTC, iloktionov commented on Vostok.Applications.Scheduled/Schedulers/PeriodicalScheduler.cs
> +        public void TryCopyStateFrom(IStatefulScheduler other)
А это имеет какое-то отношение к фиче про динамическую настройку? Есть эффект типа "если часто пересчитывается джиттер, то в какой-то момент повезёт и окажется, что экшн уже пора исполнять", но он и раньше был, вроде.

2021-05-11 14:56 UTC, iloktionov commented on Vostok.Applications.Scheduled/ScheduledActionsBuilder.cs
> +        internal List<ScheduledAction> Actions { get; }
Так это не наружу, internal же.

2021-05-11 14:58 UTC, iloktionov commented on Vostok.Applications.Scheduled/ScheduledActionsBuilder.cs
> +                throw new InvalidOperationException("Dynamic and static configuration modes can't be mixed.");
Потому что это менее понятный способ настройки (делая так, я бы не понимал, объединяются ли они и по каким правилам). Ничего же не мешает ту кодину, который ты написал бы в статичной части, просто as is перенести в динамическую, и не гадать, как именно они внутри там потом помёржатся?

2021-05-11 14:59 UTC, iloktionov commented on Vostok.Applications.Scheduled/IScheduledActionsRunner.cs
> +    public interface IScheduledActionsRunner : IDisposable
Окей, да, разумно.

2021-05-11 14:59 UTC, iloktionov commented on Vostok.Applications.Scheduled/ScheduledActionRunner.cs
> +        private volatile ScheduledAction action;
Посмотрю, где там может разъехаться, ага.

2021-05-11 15:00 UTC, iloktionov commented on Vostok.Applications.Scheduled/ScheduledActionsBuilder.cs
> +            dynamicOptions = new ScheduledActionsDynamicOptions(configuration, actualizationPeriod);
Принято.

2021-05-12 13:38 UTC, iloktionov commented on Vostok.Applications.Scheduled/ScheduledActionRunner.cs
> +        private volatile ScheduledAction action;
Починил в GetInfo. А внутри, на самом деле, даже полезно, если, например, коллбэк после выполнения стрельнёт на новом шедулере, а не на старом, потому что так будет меньше спецэффектов с планированием времени из-за пропущенных уведомлений (если коллбэк влетит в старый шедулер уже после копирования состояния оного).

2021-05-12 13:39 UTC, merged